import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Open_Sans } from "next/font/google";

const sans = Open_Sans({
  weight: ["300", "400", "500"],
  variable: "--font-sans",
  subsets: ["latin"],
  display: "block",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${sans.variable} font-sans dark  `}>
        {children}
        <Toaster richColors className="z-50" />
        <script
          src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs"
          type="module"
          async
        ></script>
      </body>
    </html>
  );
}
